#!/bin/sh

# Generate Markdown checkout tables for any-in games

dir="../tables/"

paths=(
    "london/London_any_in_any_out.md"
    "london/London_any_in_master_out.md"
    "london/London_any_in_double_out.md"
    "quadro/Quadro_any_in_any_out.md"
    "quadro/Quadro_any_in_master_out.md"
    "quadro/Quadro_any_in_double_out.md"
)

boards=(
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"
)

in_mode="any-in"

out_modes=(
    "any-out"
    "master-out"
    "double-out"
    "any-out"
    "master-out"
    "double-out"
)

requirements=(
    "without requirements on the first or last darts"
    "without requirements on the first dart"
    "without requirements on the first dart"
    "without requirements on the first or last darts"
    "without requirements on the first dart"
    "without requirements on the first dart"
)

other_mode_phrases=(
    ""
    "[master-in, master-out](London_master_in_master_out.md)"
    "[master-in, double-out](London_master_in_double_out.md) and [double-in, double-out](London_double_in_double_out.md)"
    ""
    "[master-in, master-out](Quadro_master_in_master_out.md)"
    "[master-in, double-out](Quadro_master_in_double_out.md) and [double-in, double-out](Quadro_double_in_double_out.md)"
)

other_field_phrases=(
    ""
    "double or triple"
    "double or triple"
    ""
    "double or triple"
    "double or triple"
)

selected_min_scores=(
    "  1  23  61 103 121 101     401         701     1001" # "  1  23 103 163 223 283 343 403 463"
    "  1   5  61 103 121 101     401         701     1001" # "  1   5 103 163 223 283 343 403 463"
    "  1   3  51  99 111 101     401 501     701     1001" # "  1   3  99 159 219 279 339 399 459"
    "  1  23  81 135 161     201         601         1001" # "  1  23 135 215 295 375 455 535 615"
    "  1   5  61 135 141     201         601         1001" # "  1   5 135 215 295 375 455 535 615"
    "  1   3  51  99 131 101         501         901     " # "  1   3  99 185 265 345 425 505 585"
)

selected_max_scores=(
    " 60  60 120 120 180 101     401         701     1001" # " 60 120 180 240 300 360 420 480 540"
    " 60  60 120 120 180 101     401         701     1001" # " 60 120 180 240 300 360 420 480 540"
    " 50  50 110 110 170 101     401 501     701     1001" # " 50 110 170 230 290 350 410 470 530"
    " 80  80 160 160 240     201         601         1001" # " 80 160 240 320 400 480 560 640 720"
    " 60  60 140 140 220     201         601         1001" # " 60 140 220 300 380 460 540 620 700"
    " 50  50 130 130 210 101         501         901     " # " 50 130 210 290 370 450 530 610 690"
)

commands=(
    "checkouts -j any"
    "checkouts -j master"
    "checkouts"
    "checkouts -b quadro -j any"
    "checkouts -b quadro -j master"
    "checkouts -b quadro"
)

throws=(
    "1"
    "2"
    "2"
    "3"
    "3"
)

labels=(
    "One"
    "Two"
    "Two"
    "Three"
    "Three"
)

anchors=(
    "one-dart-checkouts"
    "two-dart-checkouts"
    "two-dart-checkouts-1"
    "three-dart-checkouts"
    "three-dart-checkouts-1"
)

script_path="../../java/"

for i in "${!paths[@]}"; do
    path="${paths[i]}"
    file="${dir}${path}"

    board="${boards[i]}"
    out_mode="${out_modes[i]}"
    mode="${in_mode}, ${out_mode}"

    title="${board} ${mode} checkouts"
    subtitle="Checkout tables for ${mode} darts games with the ${board}"

    requirements_phrase="${requirements[i]}"

    other_mode_phrase="${other_mode_phrases[i]}"
    other_field_phrase="${other_field_phrases[i]}"

    {
        echo -e "# ${title}\n"

        echo -e "> ${subtitle}\n"

        echo -e "## Introduction\n"

        echo -e "This part of the [darts](https://github.com/mauritssilvis/darts) > [Markdown](../..) project provides checkout tables for darts games with the ${board} played in ${mode} mode."
        echo -e "These tables are valid for games ${requirements_phrase}."

        if [ "${other_mode_phrase}" != "" ]; then
            echo -e "However, they also apply to ${other_mode_phrase} games after the required ${other_field_phrase} has been thrown.\n"
        else
            echo ""
        fi
    } > "${file}"

    last_max_score="0"

    IFS=' ' read -ra min_scores <<< "${selected_min_scores[i]}"
    IFS=' ' read -ra max_scores <<< "${selected_max_scores[i]}"

    {
        echo -e "In ${out_mode} games with the ${board}, the last dart can score between ${min_scores[0]} and ${max_scores[0]} points."
        echo -e "The last two darts can reach ${max_scores[2]} points, and ${max_scores[4]} points can be scored with the last three."
        echo -e "The following table shows which checkout tables are provided for these scores.\n"

        echo -e "|                 Scores |                        Darts |"
        echo -e "|-----------------------:|-----------------------------:|"
    } >> "${file}"

    for j in "${!throws[@]}"; do
        min_score="${min_scores[j]}"
        max_score="${max_scores[j]}"
        num_throws="${throws[j]}"
        anchor="${anchors[j]}"

        {
            if [ "${max_score}" != "${last_max_score}" ]; then
                echo -n "| [${min_score} – ${max_score}](#${min_score}--${max_score}) "
            else
                echo -n "|                 "
            fi

            echo "| [${num_throws}](#${anchor}) |"
        } >> "${file}"

        last_max_score=${max_score}
    done

    {
        echo -e ""

        echo -e "As for ${mode} checkouts, the following can be observed."
        echo -e "Darts games commonly require players to score x01 points, where x is an integer."
        echo -e "The following table shows the required number of darts to reach such scores in ${board} ${mode} games."
        echo -e "In addition, the corresponding number of possible checkouts is shown.\n"

        echo -e "|         Score | Darts |     Checkouts |"
        echo -e "|--------------:|------:|--------------:|\n"

        echo -e "The most exciting games will be those with relatively few possible checkouts."
        echo -e "Checkout tables for these scores are given at the end of this document."
        echo -e "Additional tables can be generated using the \`darts\` toolbox of the [darts](https://github.com/mauritssilvis/darts) project.\n"
    } >> "${file}"

    for j in "${!min_scores[@]}"; do
        min_score="${min_scores[j]}"
        max_score="${max_scores[j]}"

        if [ "${j}" -lt "${#throws[@]}" ]; then
            if [ "${max_score}" != "${last_max_score}" ]; then
                headings="## ${min_score} – ${max_score}\n\n"
            else
                headings=""
            fi

            label="${labels[j]}"
            headings="${headings}### ${label}-dart checkouts"

            num_throws="${throws[j]}"
            command="${commands[i]} -n ${num_throws} ${min_score} ${max_score}"
        else
            headings="## ${min_score}"
            command="${commands[i]} ${min_score} ${max_score}"
        fi

        shell_command=("./${script_path}darts" ${command})

        {
            echo -e "${headings}\n"
            "${shell_command[@]}"
            echo -e "\nThis table was generated using the command:\n\n\`\`\`shell\ndarts ${command}\n\`\`\`\n"
        } >> "${file}"

        last_max_score=${max_score}
    done

    {
        echo -e "## License\n"
        echo -e "Copyright © 2023 Maurits Silvis\n"
        echo -e "This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file [LICENSE.md](../../../LICENSE.md), or later."
    } >> "${file}"
done
