#!/bin/sh

# Generate Markdown checkout tables for master-in and double-in darts games

path="../"

names=(
    "London_master_in_master_out"
    "London_master_in_double_out"
    "London_double_in_double_out"
    "Quadro_master_in_master_out"
    "Quadro_master_in_double_out"
    "Quadro_double_in_double_out"
)

extension=".md"

titles=(
    "London dartboard master-in master-out"
    "London dartboard master-in double-out"
    "London dartboard double-in double-out"
    "Quadro 240 board master-in master-out"
    "Quadro 240 board master-in double-out"
    "Quadro 240 board double-in double-out"
)

title_suffix="checkout tables"

commands=(
    "checkouts -i master -j master"
    "checkouts -i master"
    "checkouts -i double"
    "checkouts -b quadro -i master -j master"
    "checkouts -b quadro -i master"
    "checkouts -b quadro -i double"
)

for i in ${!names[@]}
do
    file="$path${names[i]}$extension"
    title="${titles[i]} $title_suffix"

    echo -e "# $title\n" > $file

    echo -e "## Table of contents\n" >> $file

    for j in {1..10}
    do
        score=$(($j * 100 + 1))
        echo -e "- [$score](#$score)" >> $file
    done

    echo "" >> $file

    for j in {1..10}
    do
        score=$(($j * 100 + 1))

        echo -e "## $score\n" >> $file

        command="${commands[i]} $score $score"
        echo -e "This table was generated using the command:\n\n\`\`\`shell\ndarts $command\n\`\`\`\n" >> $file
    done

    echo -e "## License\n" >> $file
    echo -e "Copyright © 2023 Maurits Silvis\n" >> $file
    echo -e "This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file [LICENSE.md](../LICENSE.md), or later." >> $file

done
