#!/bin/sh

# Generate Markdown checkout tables for master-in and double-in darts games

files=(
    "../London_master_in_master_out.md"
    "../London_master_in_double_out.md"
    "../London_double_in_double_out.md"
    "../Quadro_master_in_master_out.md"
    "../Quadro_master_in_double_out.md"
    "../Quadro_double_in_double_out.md"
)

titles=(
    "London dartboard master-in master-out checkouts"
    "London dartboard master-in double-out checkouts"
    "London dartboard double-in double-out checkouts"
    "Quadro 240 board master-in master-out checkouts"
    "Quadro 240 board master-in double-out checkouts"
    "Quadro 240 board double-in double-out checkouts"
)

commands=(
    "checkouts -i master -j master"
    "checkouts -i master"
    "checkouts -i double"
    "checkouts -b quadro -i master -j master"
    "checkouts -b quadro -i master"
    "checkouts -b quadro -i double"
)

for i in ${!files[@]}
do
    file=${files[i]}
    title=${titles[i]}

    echo -e "# $title\n" > $file

    for j in {1..10}
    do
        score=$(($j * 100 + 1))

        echo -e "## $score\n" >> $file

        command="${commands[i]} $score $score"
        echo -e "This table was generated using the command:\n\n\`\`\`shell\ndarts $command\n\`\`\`\n" >> $file
    done

    echo -e "## License\n" >> $file
    echo -e "Copyright © 2023 Maurits Silvis\n" >> $file
    echo -e "This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file [LICENSE.md](../LICENSE.md), or later." >> $file

done
