#!/bin/sh

# Generate Markdown checkout tables for selected scores

dir="../tables/"

paths=(
    "london/London_any_in_any_out.md"
    "london/London_any_in_master_out.md"
    "london/London_master_in_master_out.md"
    "london/London_any_in_double_out.md"
    "london/London_master_in_double_out.md"
    "london/London_double_in_double_out.md"
    "quadro/Quadro_any_in_any_out.md"
    "quadro/Quadro_any_in_master_out.md"
    "quadro/Quadro_master_in_master_out.md"
    "quadro/Quadro_any_in_double_out.md"
    "quadro/Quadro_master_in_double_out.md"
    "quadro/Quadro_double_in_double_out.md"
)

titles=(
    "London dartboard any-in any-out"
    "London dartboard any-in master-out"
    "London dartboard master-in master-out"
    "London dartboard any-in double-out"
    "London dartboard master-in double-out"
    "London dartboard double-in double-out"
    "Quadro 240 board any-in any-out"
    "Quadro 240 board any-in master-out"
    "Quadro 240 board master-in master-out"
    "Quadro 240 board any-in double-out"
    "Quadro 240 board master-in double-out"
    "Quadro 240 board double-in double-out"
)

title_suffix="checkout tables"

selected_scores=(
    "101 401 701 1001"
    "101 401 701 1001"
    "101 401 701 1001"
    "101 401 501 701 1001"
    "101 401 501 701 1001"
    "201 501 801"
    "201 601 1001"
    "201 601 1001"
    "101 501 901"
    "101 501 901"
    "101 501 901"
    "301 701"
)

script_path="../../java/"

commands=(
    "checkouts -j any"
    "checkouts -j master"
    "checkouts -i master -j master"
    "checkouts"
    "checkouts -i master"
    "checkouts -i double"
    "checkouts -b quadro -j any"
    "checkouts -b quadro -j master"
    "checkouts -b quadro -i master -j master"
    "checkouts -b quadro"
    "checkouts -b quadro -i master"
    "checkouts -b quadro -i double"
)

for i in "${!paths[@]}"
do
    file="${dir}${paths[i]}"
    title="${titles[i]} $title_suffix"

    echo -e "# $title\n" > $file

    echo -e "## Table of contents\n" >> $file

    IFS=' ' read -ra scores <<< "${selected_scores[i]}"

    for j in "${!scores[@]}"; do
        score=${scores[j]}
        echo -e "- [$score](#$score)" >> $file
    done

    echo "" >> $file

    IFS=' ' read -ra scores <<< "${selected_scores[i]}"

    for j in "${!scores[@]}"; do
        score=${scores[j]}
        command="${commands[i]} $score $score"

        echo -e "## $score\n" >> $file
        java -jar "${script_path}build/libs/java-darts-toolbox-0.1.0-SNAPSHOT-all.jar" $command >> $file
        echo -e "This table was generated using the command:\n\n\`\`\`shell\ndarts $command\n\`\`\`\n" >> $file
    done

    echo -e "## License\n" >> $file
    echo -e "Copyright © 2023 Maurits Silvis\n" >> $file
    echo -e "This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file [LICENSE.md](../LICENSE.md), or later." >> $file
done
