#!/bin/sh

# Generate Markdown checkout tables for selected dartboards, game modes and scores

dir="../tables/"

paths=(
    "london/London_any_in_any_out.md"
    "london/London_any_in_master_out.md"
    "london/London_master_in_master_out.md"
    "london/London_any_in_double_out.md"
    "london/London_master_in_double_out.md"
    "london/London_double_in_double_out.md"
    "quadro/Quadro_any_in_any_out.md"
    "quadro/Quadro_any_in_master_out.md"
    "quadro/Quadro_master_in_master_out.md"
    "quadro/Quadro_any_in_double_out.md"
    "quadro/Quadro_master_in_double_out.md"
    "quadro/Quadro_double_in_double_out.md"
)

boards=(
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"

)

modes=(
    "any-in, any-out"
    "any-in, master-out"
    "master-in, master-out"
    "any-in, double-out"
    "master-in, double-out"
    "double-in, double-out"
    "any-in, any-out"
    "any-in, master-out"
    "master-in, master-out"
    "any-in, double-out"
    "master-in, double-out"
    "double-in, double-out"
)

selected_scores=(
    "101 401 701 1001"
    "101 401 701 1001"
    "101 401 701 1001"
    "101 401 501 701 1001"
    "101 401 501 701 1001"
    "201 501 801"
    "201 601 1001"
    "201 601 1001"
    "101 501 901"
    "101 501 901"
    "101 501 901"
    "301 701"
)

script_path="../../java/"

commands=(
    "checkouts -j any"
    "checkouts -j master"
    "checkouts -i master -j master"
    "checkouts"
    "checkouts -i master"
    "checkouts -i double"
    "checkouts -b quadro -j any"
    "checkouts -b quadro -j master"
    "checkouts -b quadro -i master -j master"
    "checkouts -b quadro"
    "checkouts -b quadro -i master"
    "checkouts -b quadro -i double"
)

for i in "${!paths[@]}"
do
    path="${paths[i]}"
    file="${dir}${path}"
    board="${boards[i]}"
    mode="${modes[i]}"

    title="${board} ${mode} checkouts"
    subtitle="Checkout tables for ${mode} darts games with the ${board}"

    {
        echo -e "# $title\n";
        echo -e "> $subtitle\n";

        echo -e "## Introduction\n";

        echo -e "This part of the [darts](https://github.com/mauritssilvis/darts) > [Markdown](../..) project provides checkout tables for darts games with the ${board} played in ${mode} mode.\n";

        echo -e "Darts games commonly require players to score x01 points, where x is an integer.";
        echo -e "The following table shows the required number of darts to reach such scores in ${board} ${mode} games.";
        echo -e "In addition, the corresponding number of possible checkouts is shown.\n";

        echo -e "|         Score | Darts |      Checkouts |";
        echo -e "|--------------:|------:|---------------:|\n";

        echo -e "The most exciting games will be those with a comparatively small number of possible checkouts.";
        echo -e "Checkout tables for these scores are given below.";
        echo -e "Additional tables can be generated using the \`darts\` toolbox of the [darts](https://github.com/mauritssilvis/darts) project.\n";
    } > "$file"

    IFS=' ' read -ra scores <<< "${selected_scores[i]}"

    for j in "${!scores[@]}"; do
        score=${scores[j]}
        command="${commands[i]} ${score} ${score}"
        shell_command=("./${script_path}darts" ${command})

        {
            echo -e "## ${score}\n";
            "${shell_command[@]}"
            echo -e "This table was generated using the command:\n\n\`\`\`shell\ndarts ${command}\n\`\`\`\n";
        } >> "$file"
    done

    {
        echo -e "## License\n";
        echo -e "Copyright © 2023 Maurits Silvis\n";
        echo -e "This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file [LICENSE.md](../../../LICENSE.md), or later.";
    } >> "$file"
done
