#!/bin/sh

# Generate Markdown checkout tables for selected dartboards, game modes, number of throws and scores

dir="../tables_per_dart/"

paths=(
    "london/London_any_in_any_out.md"
    "london/London_any_in_master_out.md"
    "london/London_any_in_double_out.md"
    "quadro/Quadro_any_in_any_out.md"
    "quadro/Quadro_any_in_master_out.md"
    "quadro/Quadro_any_in_double_out.md"
)

boards=(
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"
)

modes=(
    "any-in, any-out"
    "any-in, master-out"
    "any-in, double-out"
    "any-in, any-out"
    "any-in, master-out"
    "any-in, double-out"
)

selected_min_scores=(
    "  1  23 103 401         701         1001" # "  1  23 103 163 223 283 343 403 463"
    "  1   5 103 401         701         1001" # "  1   5 103 163 223 283 343 403 463"
    "  1   3  99 401 501     701         1001" # "  1   3  99 159 219 279 339 399 459"
    "  1  23 135         601             1001" # "  1  23 135 215 295 375 455 535 615"
    "  1   5 135         601             1001" # "  1   5 135 215 295 375 455 535 615"
    "  1   3  99     501             901     " # "  1   3  99 185 265 345 425 505 585"
)

selected_max_scores=(
    " 60 120 180 401         701         1001" # " 60 120 180 240 300 360 420 480 540"
    " 60 120 180 401         701         1001" # " 60 120 180 240 300 360 420 480 540"
    " 50 110 170 401 501     701         1001" # " 50 110 170 230 290 350 410 470 530"
    " 80 160 240         601             1001" # " 80 160 240 320 400 480 560 640 720"
    " 60 140 220         601             1001" # " 60 140 220 300 380 460 540 620 700"
    " 50 130 210     501             901     " # " 50 130 210 290 370 450 530 610 690"
)

script_path="../../java/"

commands=(
    "checkouts -j any"
    "checkouts -j master"
    "checkouts"
    "checkouts -b quadro -j any"
    "checkouts -b quadro -j master"
    "checkouts -b quadro"
)

darts=(
    "One"
    "Two"
    "Three"
)

for i in "${!paths[@]}"; do
    path="${paths[i]}"
    file="${dir}${path}"
    board="${boards[i]}"
    mode="${modes[i]}"

    title="${board} ${mode} checkouts"
    subtitle="Checkout tables for ${mode} darts games with the ${board}"

    {
        echo -e "# ${title}\n"
        echo -e "> ${subtitle}\n"

        echo -e "## Introduction\n"

        echo -e "This part of the [darts](https://github.com/mauritssilvis/darts) > [Markdown](../..) project provides checkout tables for darts games with the ${board} played in ${mode} mode.\n"
    } > "$file"

    IFS=' ' read -ra min_scores <<< "${selected_min_scores[i]}"
    IFS=' ' read -ra max_scores <<< "${selected_max_scores[i]}"

    for j in "${!min_scores[@]}"; do
        min_score=${min_scores[j]}
        max_score=${max_scores[j]}

        if [ "${j}" -lt "${#darts[@]}" ]; then
            heading="${darts[j]}-dart checkouts"
            command="${commands[i]} -n $((j + 1)) ${min_score} ${max_score}"
        else
            heading="${min_score}"
            command="${commands[i]} ${min_score} ${max_score}"
        fi

        shell_command=("./${script_path}darts" ${command})

        {
            echo -e "## ${heading}\n"
            "${shell_command[@]}"
            echo -e "\nThis table was generated using the command:\n\n\`\`\`shell\ndarts ${command}\n\`\`\`\n"
        } >> "$file"
    done

    {
        echo -e "## License\n"
        echo -e "Copyright © 2023 Maurits Silvis\n"
        echo -e "This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file [LICENSE.md](../../../LICENSE.md), or later."
    } >> "$file"
done
