#!/bin/sh

# Generate HTML checkout tables for any-in games

dir="../"

paths=(
    "london/London_any_in_any_out.html"
    "london/London_any_in_master_out.html"
    "london/London_any_in_double_out.html"
    "quadro/Quadro_any_in_any_out.html"
    "quadro/Quadro_any_in_master_out.html"
    "quadro/Quadro_any_in_double_out.html"
)

boards=(
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"
)

in_mode="any-in"

out_modes=(
    "any-out"
    "master-out"
    "double-out"
    "any-out"
    "master-out"
    "double-out"
)

requirements=(
    "without requirements on the first (in) or last (out) darts"
    "without requirements on the first (in) dart, whereas the last (out) dart must land on a double or a triple"
    "without requirements on the first (in) dart, whereas the last (out) dart must land on a double"
    "without requirements on the first (in) or last (out) darts"
    "without requirements on the first (in) dart, whereas the last (out) dart must land on a double or a triple"
    "without requirements on the first (in) dart, whereas the last (out) dart must land on a double"
)

other_mode_phrases=(
    ""
    "<a href=\"London_master_in_master_out.html\">master-in, master-out</a>"
    "<a href=\"London_master_in_double_out.html\">master-in, double-out</a> and <a href=\"London_double_in_double_out.html\">double-in, double-out</a>"
    ""
    "<a href=\"Quadro_master_in_master_out.html\">master-in, master-out</a>"
    "<a href=\"Quadro_master_in_double_out.html\">master-in, double-out</a> and <a href=\"Quadro_double_in_double_out.html\">double-in, double-out</a>"
)

other_field_phrases=(
    ""
    "double or triple"
    "double or triple"
    ""
    "double or triple"
    "double or triple"
)

styles="
    a {
     text-decoration: none;
    }

    th,
    td {
     text-align: right;
     vertical-align: top;
    }
  "

score_ranges=(
    "1 60 120 180"
    "2 60 120 180"
    "2 50 110 170"
    "1 80 160 240"
    "2 60 140 220"
    "2 50 130 210"
)

selected_min_scores=(
    "  1  23  61 103 121 101     401         701     1001"
    "  1   5  61 103 121 101     401         701     1001"
    "  1   3  51  99 111 101     401 501     701     1001"
    "  1  23  81 135 161     201         601         1001"
    "  1   5  61 135 141     201         601         1001"
    "  1   3  51  99 131 101         501         901     "
)

selected_max_scores=(
    " 60  60 120 120 180 101     401         701     1001"
    " 60  60 120 120 180 101     401         701     1001"
    " 50  50 110 110 170 101     401 501     701     1001"
    " 80  80 160 160 240     201         601         1001"
    " 60  60 140 140 220     201         601         1001"
    " 50  50 130 130 210 101         501         901     "
)

throws=(
    "1"
    "2"
    "2"
    "3"
    "3"
)

anchors=(
    "one-dart-checkouts"
    "two-dart-checkouts"
    "two-dart-checkouts-1"
    "three-dart-checkouts"
    "three-dart-checkouts-1"
)

row_spans=(
    "2"
    ""
    "2"
    ""
    ""
)

tables=(
    '  <tr><th>                Score    </th><th>Darts</th><th>    Checkouts</th></tr>
  <tr><td> <a href="#101">  101</a></td><td>    2</td><td>            2</td></tr>
  <tr><td>                  201    </td><td>    4</td><td>          772</td></tr>
  <tr><td>                  301    </td><td>    6</td><td>       66,144</td></tr>
  <tr><td> <a href="#401">  401</a></td><td>    7</td><td>          392</td></tr>
  <tr><td>                  501    </td><td>    9</td><td>      223,026</td></tr>
  <tr><td>                  601    </td><td>   11</td><td>   24,066,702</td></tr>
  <tr><td> <a href="#701">  701</a></td><td>   12</td><td>        3,432</td></tr>
  <tr><td>                  801    </td><td>   14</td><td>   10,666,320</td></tr>
  <tr><td>                  901    </td><td>   16</td><td>1,821,306,720</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   17</td><td>       13,872</td></tr>'
    '  <tr><th>                Score    </th><th>Darts</th><th>    Checkouts</th></tr>
  <tr><td> <a href="#101">  101</a></td><td>    2</td><td>            2</td></tr>
  <tr><td>                  201    </td><td>    4</td><td>          772</td></tr>
  <tr><td>                  301    </td><td>    6</td><td>       65,007</td></tr>
  <tr><td> <a href="#401">  401</a></td><td>    7</td><td>          392</td></tr>
  <tr><td>                  501    </td><td>    9</td><td>      223,026</td></tr>
  <tr><td>                  601    </td><td>   11</td><td>   24,032,174</td></tr>
  <tr><td> <a href="#701">  701</a></td><td>   12</td><td>        3,432</td></tr>
  <tr><td>                  801    </td><td>   14</td><td>   10,666,320</td></tr>
  <tr><td>                  901    </td><td>   16</td><td>1,820,922,471</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   17</td><td>       13,872</td></tr>'
    '  <tr><th>                Score    </th><th>Darts</th><th>  Checkouts</th></tr>
  <tr><td> <a href="#101">  101</a></td><td>    2</td><td>          1</td></tr>
  <tr><td>                  201    </td><td>    4</td><td>         73</td></tr>
  <tr><td>                  301    </td><td>    6</td><td>     15,681</td></tr>
  <tr><td> <a href="#401">  401</a></td><td>    7</td><td>         56</td></tr>
  <tr><td> <a href="#501">  501</a></td><td>    9</td><td>      3,944</td></tr>
  <tr><td>                  601    </td><td>   11</td><td>  3,658,382</td></tr>
  <tr><td> <a href="#701">  701</a></td><td>   12</td><td>        286</td></tr>
  <tr><td>                  801    </td><td>   14</td><td>     38,740</td></tr>
  <tr><td>                  901    </td><td>   16</td><td>202,772,073</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   17</td><td>        816</td></tr>'
    '  <tr><th>                Score    </th><th>Darts</th><th> Checkouts</th></tr>
  <tr><td>                  101    </td><td>    2</td><td>        12</td></tr>
  <tr><td> <a href="#201">  201</a></td><td>    3</td><td>        21</td></tr>
  <tr><td>                  301    </td><td>    5</td><td>    62,970</td></tr>
  <tr><td>                  401    </td><td>    6</td><td>    56,952</td></tr>
  <tr><td>                  501    </td><td>    7</td><td>    21,301</td></tr>
  <tr><td> <a href="#601">  601</a></td><td>    8</td><td>     1,736</td></tr>
  <tr><td>                  701    </td><td>   10</td><td>67,297,690</td></tr>
  <tr><td>                  801    </td><td>   11</td><td>15,375,723</td></tr>
  <tr><td>                  901    </td><td>   12</td><td> 1,306,680</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   13</td><td>    17,901</td></tr>'
    '  <tr><th>                Score    </th><th>Darts</th><th> Checkouts</th></tr>
  <tr><td>                  101    </td><td>    2</td><td>         6</td></tr>
  <tr><td> <a href="#201">  201</a></td><td>    3</td><td>         7</td></tr>
  <tr><td>                  301    </td><td>    5</td><td>    21,061</td></tr>
  <tr><td>                  401    </td><td>    6</td><td>    13,631</td></tr>
  <tr><td>                  501    </td><td>    7</td><td>     3,553</td></tr>
  <tr><td> <a href="#601">  601</a></td><td>    8</td><td>       217</td></tr>
  <tr><td>                  701    </td><td>   10</td><td>10,595,757</td></tr>
  <tr><td>                  801    </td><td>   11</td><td> 1,789,517</td></tr>
  <tr><td>                  901    </td><td>   12</td><td>   117,085</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   13</td><td>     1,377</td></tr>'
    '  <tr><th>              Score    </th><th>Darts</th><th>  Checkouts</th></tr>
  <tr><td<a href="#101">  101</a></td><td>    2</td><td>          1</td></tr>
  <tr><td>                201    </td><td>    4</td><td>      3,244</td></tr>
  <tr><td>                301    </td><td>    5</td><td>      3,412</td></tr>
  <tr><td>                401    </td><td>    6</td><td>        820</td></tr>
  <tr><td<a href="#501">  501</a></td><td>    7</td><td>          6</td></tr>
  <tr><td>                601    </td><td>    9</td><td>  4,207,648</td></tr>
  <tr><td>                701    </td><td>   10</td><td>    642,234</td></tr>
  <tr><td>                801    </td><td>   11</td><td>     21,300</td></tr>
  <tr><td<a href="#901">  901</a></td><td>   12</td><td>         11</td></tr>
  <tr><td>               1001    </td><td>   14</td><td>449,392,814</td></tr>'
)

other_table_scores=(
    ""
    ""
    "501"
    ""
    ""
    ""
)

labels=(
    "One"
    "Two"
    "Two"
    "Three"
    "Three"
)

commands=(
    "checkouts -j any"
    "checkouts -j master"
    "checkouts"
    "checkouts -b quadro -j any"
    "checkouts -b quadro -j master"
    "checkouts -b quadro"
)

script_path="../../../cli/java-darts-cli/bin/"

for i in "${!paths[@]}"; do
    path="${paths[i]}"
    file="${dir}${path}"

    board="${boards[i]}"
    out_mode="${out_modes[i]}"
    mode="${in_mode}, ${out_mode}"

    title="${board} ${mode} checkouts"
    subtitle="Checkout tables for ${mode} darts games with the ${board}"

    requirements_phrase="${requirements[i]}"

    other_mode_phrase="${other_mode_phrases[i]}"
    other_field_phrase="${other_field_phrases[i]}"

    {
        echo "<!DOCTYPE html>"
        echo "<html lang=\"en-US\">"
        echo "<head>"
        echo "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">"
        echo "  <title>${title}</title>"
        echo "  <style>${styles}</style>"
        echo "</head>"
        echo "<body>"
        echo "  <div class=\"container\">"
        echo "    <h1>${title}</h1>"

        echo "    <blockquote class=\"text-secondary\">${subtitle}</blockquote>"

        echo "    <h2 class=\"pb-1 border-bottom mb-3\">Introduction</h2>"

        echo "    <p>"
        echo "      This part of the <a href=\"https://github.com/mauritssilvis/darts\">darts</a> > <a href=\"https://github.com/mauritssilvis/darts/tree/main/tables\">Tables</a> > <a href=\"..\">HTML</a> project provides checkout tables for darts games with the ${board} played in ${mode} mode."
        echo "      These tables are valid for games ${requirements_phrase}."

        if [ "${other_mode_phrase}" != "" ]; then
            echo "      However, these tables also apply to ${other_mode_phrase} games after the required ${other_field_phrase} has been thrown."
        fi

        echo "    </p>"
    } > "${file}"

    last_max_score="0"

    IFS=' ' read -ra score_range <<< "${score_ranges[i]}"
    IFS=' ' read -ra min_scores <<< "${selected_min_scores[i]}"
    IFS=' ' read -ra max_scores <<< "${selected_max_scores[i]}"

    {
        echo "    <p>"
        echo "      In ${out_mode} games with the ${board}, the last dart can score between ${score_range[0]} and ${score_range[1]} points."
        echo "      The last two darts can reach ${score_range[2]} points, and ${score_range[3]} points can be scored with the last three."
        echo "      The following table shows which checkout tables are provided for these scores."
        echo "    </p>"

        echo "<table class=\"table w-auto\">"
        echo "  <tr><th>Scores</th><th>Darts</th></tr>"
    } >> "${file}"

    for j in "${!throws[@]}"; do
        min_score="${min_scores[j]}"
        max_score="${max_scores[j]}"
        num_throws="${throws[j]}"
        anchor="${anchors[j]}"
        row_span="${row_spans[j]}"

        {
            echo -n "  <tr>"

            if [ "${max_score}" != "${last_max_score}" ]; then
                if [ "${row_span}" != "" ]; then
                    echo -n "<th rowspan=\"${row_span}\" scope=\"rowgroup\" class=\"fw-normal\">"
                else
                    echo -n "<th class=\"fw-normal\">"
                fi

                echo -n "<a href=\"#${min_score}--${max_score}\">${min_score} – ${max_score}</a></th>"
            fi

            echo "<td><a href=\"#${anchor}\">${num_throws}</a></td></tr>"
        } >> "${file}"

        last_max_score=${max_score}
    done

    {
        echo "</table>"
    } >> "${file}"

    table="${tables[i]}"
    other_table_score="${other_table_scores[i]}"

    {
        echo "    <p>"
        echo "      As for ${mode} checkouts, the following can be observed."
        echo "      Darts games commonly require players to score x01 points, where x is an integer."
        echo "      The following table shows the required number of darts to reach such scores in ${board} ${mode} games."
        echo "      In addition, the corresponding number of possible checkouts is shown."
        echo "    </p>"

        echo "<table class=\"table w-auto\">"
        echo "${table}"
        echo "</table>"

        echo "    <p>"
        echo "      The most exciting games will be those with relatively few possible checkouts."
        echo "      Checkout tables for these scores are given at the end of this document."

        if [ "${other_table_score}" != "" ]; then
            echo "      A checkout table for ${other_table_score} points was included as it is a typical score in darts games."
        fi

        echo "      Additional tables can be generated using the <code>darts</code> toolbox of the <a href=\"https://github.com/mauritssilvis/darts\">darts</a> project."
        echo "    </p>"
    } >> "${file}"

    for j in "${!min_scores[@]}"; do
        min_score="${min_scores[j]}"
        max_score="${max_scores[j]}"

        if [ "${j}" -lt "${#throws[@]}" ]; then
            if [ "${max_score}" != "${last_max_score}" ]; then
                headings="    <h2 id=\"${min_score}--${max_score}\" class=\"pb-1 border-bottom mb-3\">${min_score} – ${max_score}</h2>\n"
            else
                headings=""
            fi

            label="${labels[j]}"
            anchor="${anchors[j]}"
            headings="${headings}    <h3 id=\"${anchor}\">${label}-dart checkouts</h3>"

            num_throws="${throws[j]}"
            command="${commands[i]} -n ${num_throws} -o html ${min_score} ${max_score}"
        else
            headings="    <h2 id=\"${min_score}\" class=\"pb-1 border-bottom mb-3\">${min_score}</h2>"
            command="${commands[i]} -o html ${min_score} ${max_score}"
        fi

        shell_command=("./${script_path}darts" ${command})

        {
            echo -e "${headings}"
            echo "    <div class=\"table-responsive mb-3\">"
            "${shell_command[@]}" | sed "s|<table>|<table class=\"table w-auto mb-0\">|g" | sed "s| class=\"\\w\"||g" | sed -r "s|</span><span> *| / |g" | sed -r "s|</?span>||g" | sed -r "s|> +|>|g"
            echo "    </div>"
            echo "    <p>"
            echo "      This table was generated using the command:"
            echo "    </p>"
            echo "    <pre>darts ${command}</pre>"
        } >> "${file}"

        last_max_score=${max_score}
    done

    {
        echo "    <h2 class=\"pb-1 border-bottom mb-3\">License</h2>"

        echo "    <p>"
        echo "      Copyright © 2023 Maurits Silvis"
        echo "    </p>"

        echo "    <p>"
        echo "      This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file <a href=\"../LICENSE.md\">LICENSE.md</a>, or later."
        echo "    </p>"

        echo "  </div>"
        echo "</body>"
        echo "</html>"
    } >> "${file}"
done
