#!/bin/sh

# Generate HTML checkout tables for double-in and master-in games

dir="../"

paths=(
    "london/London_master_in_master_out.html"
    "london/London_master_in_double_out.html"
    "london/London_double_in_double_out.html"
    "quadro/Quadro_master_in_master_out.html"
    "quadro/Quadro_master_in_double_out.html"
    "quadro/Quadro_double_in_double_out.html"
)

boards=(
    "London dartboard"
    "London dartboard"
    "London dartboard"
    "Quadro 240 board"
    "Quadro 240 board"
    "Quadro 240 board"

)

in_modes=(
    "master-in"
    "master-in"
    "double-in"
    "master-in"
    "master-in"
    "double-in"
)

out_modes=(
    "master-out"
    "double-out"
    "double-out"
    "master-out"
    "double-out"
    "double-out"
)

requirements=(
    "where the first (in) and last (out) darts must land on a double or triple"
    "where the first (in) dart must land on a double or a triple, and the last (out) dart must land on a double"
    "where the first (in) and last (out) darts must land on a double"
    "where the first (in) and last (out) darts must land on a double or triple"
    "where the first (in) dart must land on a double or a triple, and the last (out) dart must land on a double"
    "where the first (in) and last (out) darts must land on a double"
)

score_ranges=(
    "2 60 120 180"
    "2 50 110 170"
    "2 50 110 170"
    "2 60 140 220"
    "2 50 130 210"
    "2 50 130 210"
)

first_dart_phrases=(
    "double or triple"
    "double or triple"
    "double"
    "double or triple"
    "double or triple"
    "double"
)

other_paths=(
    "London_any_in_master_out.html"
    "London_any_in_double_out.html"
    "London_any_in_double_out.html"
    "Quadro_any_in_master_out.html"
    "Quadro_any_in_double_out.html"
    "Quadro_any_in_double_out.html"
)

tables=(
    '  <tr><th>                Score    </th><th>Darts</th><th>    Checkouts</th></tr>
  <tr><td> <a href="#101">  101</a></td><td>    2</td><td>            2</td></tr>
  <tr><td>                  201    </td><td>    4</td><td>          772</td></tr>
  <tr><td>                  301    </td><td>    6</td><td>       63,870</td></tr>
  <tr><td> <a href="#401">  401</a></td><td>    7</td><td>          392</td></tr>
  <tr><td>                  501    </td><td>    9</td><td>      223,026</td></tr>
  <tr><td>                  601    </td><td>   11</td><td>   23,997,646</td></tr>
  <tr><td> <a href="#701">  701</a></td><td>   12</td><td>        3,432</td></tr>
  <tr><td>                  801    </td><td>   14</td><td>   10,666,320</td></tr>
  <tr><td>                  901    </td><td>   16</td><td>1,820,538,222</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   17</td><td>       13,872</td></tr>'
    '  <tr><th>                Score    </th><th>Darts</th><th>  Checkouts</th></tr>
  <tr><td> <a href="#101">  101</a></td><td>    2</td><td>          1</td></tr>
  <tr><td>                  201    </td><td>    4</td><td>         73</td></tr>
  <tr><td>                  301    </td><td>    6</td><td>     15,645</td></tr>
  <tr><td> <a href="#401">  401</a></td><td>    7</td><td>         56</td></tr>
  <tr><td> <a href="#501">  501</a></td><td>    9</td><td>      3,944</td></tr>
  <tr><td>                  601    </td><td>   11</td><td>  3,658,161</td></tr>
  <tr><td> <a href="#701">  701</a></td><td>   12</td><td>        286</td></tr>
  <tr><td>                  801    </td><td>   14</td><td>     38,740</td></tr>
  <tr><td>                  901    </td><td>   16</td><td>202,771,392</td></tr>
  <tr><td><a href="#1001"> 1001</a></td><td>   17</td><td>        816</td></tr>'
    '  <tr><th>               Score    </th><th>Darts</th><th>    Checkouts</th></tr>
  <tr><td>                 101    </td><td>    3</td><td>           98</td></tr>
  <tr><td><a href="#201">  201</a></td><td>    4</td><td>           14</td></tr>
  <tr><td>                 301    </td><td>    6</td><td>        2,544</td></tr>
  <tr><td>                 401    </td><td>    8</td><td>      380,228</td></tr>
  <tr><td><a href="#501">  501</a></td><td>    9</td><td>          574</td></tr>
  <tr><td>                 601    </td><td>   11</td><td>      319,586</td></tr>
  <tr><td>                 701    </td><td>   13</td><td>   64,693,283</td></tr>
  <tr><td><a href="#801">  801</a></td><td>   14</td><td>        4,184</td></tr>
  <tr><td>                 901    </td><td>   16</td><td>   12,139,768</td></tr>
  <tr><td>                1001    </td><td>   18</td><td>3,400,574,560</td></tr>'
    '  <tr><th>               Score    </th><th>Darts</th><th>  Checkouts</th></tr>
  <tr><td><a href="#101">  101</a></td><td>    2</td><td>          2</td></tr>
  <tr><td>                 201    </td><td>    4</td><td>      5,384</td></tr>
  <tr><td>                 301    </td><td>    5</td><td>      5,795</td></tr>
  <tr><td>                 401    </td><td>    6</td><td>      1,950</td></tr>
  <tr><td><a href="#501">  501</a></td><td>    7</td><td>        172</td></tr>
  <tr><td>                 601    </td><td>    9</td><td>  5,237,514</td></tr>
  <tr><td>                 701    </td><td>   10</td><td>  1,028,526</td></tr>
  <tr><td>                 801    </td><td>   11</td><td>     83,056</td></tr>
  <tr><td><a href="#901">  901</a></td><td>   12</td><td>      1,492</td></tr>
  <tr><td>                1001    </td><td>   14</td><td>557,589,546</td></tr>'
    '  <tr><th>               Score    </th><th>Darts</th><th> Checkouts</th></tr>
  <tr><td><a href="#101">  101</a></td><td>    2</td><td>         1</td></tr>
  <tr><td>                 201    </td><td>    4</td><td>     1,428</td></tr>
  <tr><td>                 301    </td><td>    5</td><td>     1,084</td></tr>
  <tr><td>                 401    </td><td>    6</td><td>       172</td></tr>
  <tr><td><a href="#501">  501</a></td><td>    7</td><td>         1</td></tr>
  <tr><td>                 601    </td><td>    9</td><td>   763,923</td></tr>
  <tr><td>                 701    </td><td>   10</td><td>    85,068</td></tr>
  <tr><td>                 801    </td><td>   11</td><td>     2,148</td></tr>
  <tr><td><a href="#901">  901</a></td><td>   12</td><td>         1</td></tr>
  <tr><td>                1001    </td><td>   14</td><td>46,245,501</td></tr>'
    '  <tr><th>               Score    </th><th>Darts</th><th>  Checkouts</th></tr>
  <tr><td>                 101    </td><td>    3</td><td>         98</td></tr>
  <tr><td>                 201    </td><td>    4</td><td>        190</td></tr>
  <tr><td><a href="#301">  301</a></td><td>    5</td><td>         45</td></tr>
  <tr><td>                 401    </td><td>    7</td><td>    758,455</td></tr>
  <tr><td>                 501    </td><td>    8</td><td>    310,486</td></tr>
  <tr><td>                 601    </td><td>    9</td><td>     46,676</td></tr>
  <tr><td><a href="#701">  701</a></td><td>   10</td><td>      1,880</td></tr>
  <tr><td>                 801    </td><td>   12</td><td>277,420,080</td></tr>
  <tr><td>                 901    </td><td>   13</td><td> 34,829,663</td></tr>
  <tr><td>                1001    </td><td>   14</td><td>  1,752,252</td></tr>'
)

other_table_scores=(
    ""
    "501"
    ""
    ""
    ""
    ""
)

selected_scores=(
    "101         401         701         1001"
    "101         401 501     701         1001"
    "    201         501         801         "
    "101             501             901     "
    "101             501             901     "
    "        301 701"
)

commands=(
    "checkouts -i master -j master"
    "checkouts -i master"
    "checkouts -i double"
    "checkouts -b quadro -i master -j master"
    "checkouts -b quadro -i master"
    "checkouts -b quadro -i double"
)

script_path="../../../cli/java-darts-cli/bin/"

for i in "${!paths[@]}"; do
    path="${paths[i]}"
    file="${dir}${path}"

    board="${boards[i]}"
    in_mode=${in_modes[i]}
    out_mode=${out_modes[i]}
    mode="${in_mode}, ${out_mode}"

    title="${board} ${mode} checkouts"
    subtitle="Checkout tables for ${mode} darts games with the ${board}"

    requirements_phrase="${requirements[i]}"

    IFS=' ' read -ra score_range <<< "${score_ranges[i]}"

    first_dart_phrase="${first_dart_phrases[i]}"
    other_path="${other_paths[i]}"

    table="${tables[i]}"
    other_table_score="${other_table_scores[i]}"

    {
        echo "<!DOCTYPE html>"
        echo "<html lang=\"en-US\">"
        echo "  <head>"
        echo "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">"
        echo "    <title>${title}</title>"
        echo "    <style>"
        echo "      th,"
        echo "      td {"
        echo "        text-align: right;"
        echo "        vertical-align: top;"
        echo "      }"
        echo "    </style>"
        echo "  </head>"
        echo "  <body>"
        echo "    <div class=\"container\">"
        echo "      <h1>${title}</h1>"

        echo "      <blockquote>${subtitle}</blockquote>"

        echo "      <h2>Introduction</h2>"

        echo "      <p>"
        echo "        This part of the <a href=\"https://github.com/mauritssilvis/darts\">darts</a> > <a href=\"https://github.com/mauritssilvis/darts/tree/main/tables\">Tables</a> > <a href=\"..\">HTML</a> project provides checkout tables for darts games with the ${board} played in ${mode} mode."
        echo "        These tables are valid for games ${requirements_phrase}."
        echo "      </p>"

        echo "      <p>"
        echo "        In ${out_mode} games with the ${board}, the last dart can score between ${score_range[0]} and ${score_range[1]} points."
        echo "        The last two darts can reach ${score_range[2]} points, and ${score_range[3]} points can be scored with the last three."
        echo "        After a ${first_dart_phrase} has been thrown, the extensive <a href=\"${other_path}\">any-in, ${out_mode} checkout tables</a> apply to these scores."
        echo "      </p>"

        echo "      <p>"
        echo "        As for ${mode} checkouts, the following can be observed."
        echo "        Darts games commonly require players to score x01 points, where x is an integer."
        echo "        The following table shows the required number of darts to reach such scores in ${board} ${mode} games."
        echo "        In addition, the corresponding number of possible checkouts is shown."
        echo "      </p>"

        echo "<table class=\"table w-auto\">"
        echo "${table}"
        echo "</table>"

        echo "      <p>"
        echo "        The most exciting games will be those with relatively few possible checkouts."
        echo "        Checkout tables for these scores are given below."

        if [ "${other_table_score}" != "" ]; then
            echo "        A checkout table for ${other_table_score} points was included as it is a typical score in darts games."
        fi

        echo "        Additional tables can be generated using the <code>darts</code> toolbox of the <a href=\"https://github.com/mauritssilvis/darts\">darts</a> project."
        echo "      </p>"
    } > "${file}"

    IFS=' ' read -ra scores <<< "${selected_scores[i]}"

    for j in "${!scores[@]}"; do
        score=${scores[j]}
        command="${commands[i]} -o html ${score} ${score}"
        shell_command=("./${script_path}darts" ${command})

        {
            echo "      <h2 id=\"${score}\">${score}</h2>"
            "${shell_command[@]}" | sed "s|<table>|<table class=\"table w-auto\">|g" | sed "s| class=\"\\w\"||g" | sed -r "s|</?span>||g" | sed -r "s|> +|>|g"
            echo "      <p>"
            echo "        This table was generated using the command:"
            echo "      </p>"
            echo "      <pre>darts ${command}</pre>"
        } >> "${file}"
    done

    {
        echo "      <h2>License</h2>"

        echo "      <p>"
        echo "        Copyright © 2023 Maurits Silvis"
        echo "      </p>"
        echo "      <p>"
        echo "        This source code package is subject to the terms and conditions defined in the GNU General Public License v3.0, which can be found in the file <a href=\"../LICENSE.md\">LICENSE.md</a>, or later."
        echo "      </p>"

        echo "    </div>"
        echo "  </body>"
        echo "</html>"
    } >> "${file}"
done
