#!/bin/sh

# Project name
name="HTML darts tables"

# Project label
label="html-darts-tables"

# Subproject names
name_prefix="HTML darts"

names=(
    "tables"
)

# Subproject labels
label_prefix="html-darts"

labels=(
    "tables"
)

# Other files
other_files=(
    "api"
    "cli"
    "core"
)
