#!/bin/sh

# Project names
name_prefix="HTML darts"

names=(
    "tables"
)

# Project labels
label_prefix="html-darts"

labels=(
    "tables"
)

# Other files
other_files=(
    "api"
    "cli"
    "core"
)
