#!/bin/sh

# Project name
name="Java darts"

# Subproject names
name_prefix="Java darts"

names=(
    "API"
    "core"
    "CLI"
)

# Subproject labels
label_prefix="java-darts"

labels=(
    "api"
    "core"
    "cli"
)

# Other files
other_files=(
    "tables"
)
