#!/bin/sh

# Get properties
. ./java-darts-properties

# Close and release
cd ..

for i in "${!labels[@]}"; do
    label="${labels[i]}"
    project="${label_prefix}-${label}"
    path="${label}/${project}"

    echo "${project}"
    cd "${path}" || exit

    ./gradlew findSonatypeStagingRepository closeAndReleaseSonatypeStagingRepository

    cd ../..
    echo ""
done
