#!/bin/sh

# Check version
if [ $# -eq 0 ]; then
    echo "Error: No version supplied."
    exit
fi

version=${1}

# Check branch
branch=$(git rev-parse --abbrev-ref HEAD)

if [ "${branch}" != "main" ]; then
    echo "Error: Not on main branch."
    exit
fi

# Set properties
name_prefix="Java darts"

names=(
    "API"
    "core"
    "CLI"
)

label_prefix="java-darts"

labels=(
    "api"
    "core"
    "cli"
)

# Tag
for i in "${!names[@]}"; do
    name="${name_prefix} ${names[i]} ${version}"
    label="${label_prefix}-${labels[i]}-${version}"
    git tag -am "\"${name}\"" "${label}"
done
