#!/bin/bash

# Check version
if [ $# -eq 0 ]; then
    echo "Error: No version supplied."
    exit
fi

version=${1}

# Check branch
branch=$(git rev-parse --abbrev-ref HEAD)

if [ "${branch}" != "main" ]; then
    echo "Warning: Not on main branch."
fi

# Clone repository
cd ..
git clone . "../darts-${version}" 2>/dev/null
cd "../darts-${version}" || exit

# Set properties
label_prefix="java-darts"

labels=(
    "api"
    "core"
    "cli"
)

# Zip
echo -n "" > "zip.log"

for i in "${!labels[@]}"; do
    label="${labels[i]}"
    project="${label_prefix}-${label}"
    path="${label}/${project}"
    name="${label_prefix}-${label}-${version}"

    mv "${path}" "${project}" 2>/dev/null
    rm -rf "${label}"
    rm -rf "${project}/.idea"

    # .tar.gz
    rm -f "${name}.tar.gz"
    7z a "${name}.tar" "./${project}/*" >> "zip.log" 2>> "zip.log"
    7z a "${name}.tar.gz" "${name}.tar" >> "zip.log" 2>> "zip.log"
    rm -f "${name}.tar"

    # .zip
    rm -f "${name}.zip"
    7z a "${name}.zip" "./${project}/*" >> "zip.log" 2>> "zip.log"
done
