#!/bin/sh

# Project names
name_prefix="Markdown darts"

names=(
    "tables"
)

# Project labels
label_prefix="md-darts"

labels=(
    "tables"
)

# Other files
other_files=(
    "api"
    "cli"
    "core"
)

