#!/bin/sh

# Project name
name="Markdown darts tables"

# Project label
label="md-darts-tables"

# Subproject names
name_prefix="Markdown darts"

names=(
    "tables"
)

# Subproject labels
label_prefix="md-darts"

labels=(
    "tables"
)

# Other files
other_files=(
    "api"
    "cli"
    "core"
)
